<!DOCTYPE html> 
<html lang="en">
  <head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8">
    <!-- Framework CSS -->
    <link rel="stylesheet" href="<?php echo $this->baseUrl();?>/blueprint/screen.css" type="text/css" media="screen, projection">
    <link rel="stylesheet" href="<?php echo $this->baseUrl();?>/blueprint/print.css" type="text/css" media="print">
    <!--[if lt IE 8]><link rel="stylesheet" href="<?php echo $this->baseUrl();?>/blueprint/ie.css" type="text/css" media="screen, projection"><![endif]-->
    <style type="text/css" media="screen">
      p, table, hr, .box { margin-bottom:25px; }
      .box p { margin-bottom:10px; }
    </style>
    <link rel="stylesheet" href="<?php echo $this->baseUrl(); ?>/css/site.css" type="text/css" media="screen, projection">

	<script language="javascript" type="text/javascript" src="<?php echo $this->baseUrl();?>/js/jquery.js"></script>
	<script language="javascript" type="text/javascript" src="<?php echo $this->baseUrl();?>/js/jquery.coolfieldset.js"></script>
	<link rel="stylesheet" type="text/css" href="<?php echo $this->baseUrl();?>/css/jquery.coolfieldset.css" />
    
	<?php echo $this->headMeta(); ?>	
	<?php echo $this->headTitle(); ?>
  </head>
  <body>

    <div class="container">
      <h1><a href="<?php echo $this->url(array('module'=>'admin',
		'controller'=>'index','action'=>'index')); ?>">Dashboard</a></h1>
      <hr />
		<div class="span-5">
			<!--  menu -->
			<ul>
				
				<li>
				<a href="<?php echo $this->url(array('module'=>'admin',
			'controller'=>'business','action'=>'index')); ?>">Listings</a>
				</li>
				<li>
				<a href="<?php echo $this->url(array('module'=>'admin',
			'controller'=>'jobs','action'=>'index')); ?>">Jobs</a>
				</li>
				<li>
				<a href="<?php echo $this->url(array('module'=>'admin',
			'controller'=>'page','action'=>'index')); ?>">Pages</a>
				</li>				
				<li>				
				<a href="<?php echo $this->url(array('module'=>'admin',
			'controller'=>'category','action'=>'index')); ?>">Categories</a>
				</li>
				<li>
				<a href="<?php echo $this->url(array('module'=>'admin',
			'controller'=>'location','action'=>'index')); ?>">Locations</a>
				</li>
						
			</ul>
		
		</div><!-- end of div class="span-5" -->
		<div class="span-19 last">
			<?php echo $this->layout()->content; ?>
		</div><!-- end of div class="span-19 last" -->
	<hr />
      <p><a href="http://validator.w3.org/check?uri=referer">
        <img src="/images/validator.png" alt="Valid HTML 4.01 Strict" class="top"></a></p>

    </div><!-- end of div class="container" -->
  </body>
</html>

