<!DOCTYPE html PUBLIC "-//W3C//DTD HTML 4.01//EN"
   "http://www.w3.org/TR/html4/strict.dtd">

<html lang="en">
  <head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8">
    <!-- Framework CSS -->
    <link rel="stylesheet" href="<?php echo $this->baseUrl(); ?>/blueprint/screen.css" type="text/css" media="screen, projection">
    <link rel="stylesheet" href="<?php echo $this->baseUrl(); ?>/blueprint/print.css" type="text/css" media="print">
    <!--[if lt IE 8]><link rel="stylesheet" href="<?php echo $this->baseUrl(); ?>/blueprint/ie.css" type="text/css" media="screen, projection"><![endif]-->
    <style type="text/css" media="screen">
      p, table, hr, .box { margin-bottom:25px; }
      .box p { margin-bottom:10px; }
    </style>
    <link rel="stylesheet" href="<?php echo $this->baseUrl(); ?>/css/site.css" type="text/css" media="screen, projection">
	<?php echo $this->headMeta(); ?>
	<?php echo $this->headTitle(); ?>
  </head>
  <body>

    <div class="container">
	  <div class="span-24" id="Header">
	  	<div class="span-16">
      	<h1>Directory360</h1>      	
      	</div>
      	<div id="HeaderMenu" class="span-8 last">
      		<div id="SignUp">
      			<ul class="HeaderMenu"><li>Sign in</li> | <li>Register</li></ul>
      		</div>
      		<div class="clear"></div>
      		<div id="MainMenu">
      			<ul class="HeaderMenu"><li>Home</li> | <li>About</li></ul>
      		</div>
      	</div>
      </div>
      <hr>
      <p>Welcome to directory360.</p>
      <div class="span-24">
		<?php echo $this->layout()->content; ?>
	  </div>
      <p><a href="http://validator.w3.org/check?uri=referer">Valid HTML 4.01 Strict
        </a></p>

    </div>
  </body>
</html>

