<!DOCTYPE html> 
<html lang="en">
  <head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8">
    <!-- Framework CSS -->
    <link rel="stylesheet" href="<?php echo $this->baseUrl(); ?>/blueprint/screen.css" type="text/css" media="screen, projection">
    <link rel="stylesheet" href="<?php echo $this->baseUrl(); ?>/blueprint/print.css" type="text/css" media="print">
    <!--[if lt IE 8]><link rel="stylesheet" href="<?php echo $this->baseUrl(); ?>/blueprint/ie.css" type="text/css" media="screen, projection"><![endif]-->
    <style type="text/css" media="screen">
      p, table, hr, .box { margin-bottom:25px; }
      .box p { margin-bottom:10px; }
    </style>
    <link rel="stylesheet" href="<?php echo $this->baseUrl(); ?>/css/site.css" type="text/css" media="screen, projection">
	<?php echo $this->headMeta(); ?>
	<?php echo $this->headTitle(); ?>
  </head>
  <body>

    <div class="container">
	  <div class="span-24" id="Header">
	  	<div class="span-16">
      	<h1>Directory360</h1>      	
      	</div>
      	<div id="HeaderMenu" class="span-8 last">
      		<div id="SignUp">
      			<ul class="HeaderMenu">
				<li><a href="<?php echo $this->url(array('controller'=>'user','action'=>'login'));?>">Sign in</a></li>
				| <li><a href="<?php echo $this->url(array('controller'=>'user','action'=>'register'));?>">Register</a></li></ul>
      		</div>
      		<div class="clear"></div>
      		<div id="MainMenu">
      			<ul class="HeaderMenu"><li>Home</li> | <li>About</li> | <li>Listing</li> | <li>Jobs</li> | <li>Contact</li></ul>
      		</div>
      	</div>
      </div>
      <hr>      
      <div class="span-24 Content">      
		<?php echo $this->layout()->content; ?>
	  </div>
	  <div class="span-24 Footer">
      <p><a href="http://validator.w3.org/check?uri=referer"><img src="<?php echo $this->baseUrl(); ?>/images/validator.png" alt="Valid HTML 4.01 Strict" class="top"></a></p>
	  </div>		
    </div>
  </body>
</html>

