<?php 
if(isset($this->messages)){
	$message = implode($this->messages); 
	$this->title = $message;
	echo '<div id="message" class="notice">'.$message.'</div>';
}
else
	$this->title = "Manage business listing";
	
$this->headTitle($this->title);
?>
<h3><?php echo $this->title; ?></h3>
<p><a href="<?php echo $this->url(array('module'=>'admin','controller'=>'business',
'action'=>'add'));?>">Add new</a></p>
<table>
<tr>
	<th>Title</th>
	<th>Status</th>
	<th>Created</th>
	<th>Action</th>
</tr>
<?php
foreach($this->records as $r){
	echo "<tr>\n";
		echo "<td>".$r['Directory_Model_Page']['Title']."</td>\n";
		echo "<td>";
		if($r['Directory_Model_Page']['Status'])
			echo 'Published';
		else
			echo 'Draft';
		echo "</td>\n";		
		echo "<td>".$r['Directory_Model_Page']['Created']."</td>\n";
		echo "<td>";
		echo '<a href="'.$this->url(array('module'=>'admin',
		'controller'=>'page','action'=>'edit','id'=>$r['PageID'])).'">Edit</a>';
		echo ' | ';
		echo '<a href="'.$this->url(array('module'=>'admin',
		'controller'=>'page','action'=>'delete','id'=>$r['PageID'])).'">Delete</a>';		
		echo "</td>\n";	
	echo "</tr>\n";	
}
?>
</table>